config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :schedules
  resources :tables
  resources :restaurants
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :table
  validate :should_not_overlap, :valid_slot#, on: :create
  #validate :valid_slot, on: :update

  def should_not_overlap
    if table.reservations.where("time_from <= ? AND time_to > ? AND NOT id = ?", time_from, time_from, id).count > 0
      errors.add(:time_from, "shouldn't overlap with existing reservation")
    end
    if table.reservations.where("time_from < ? AND time_to >= ? AND NOT id = ?", time_to, time_to, id).count > 0
      errors.add(:time_from, "shouldn't overlap with existing reservation")
    end
    if table.reservations.where("time_from >= ? AND time_to <= ? AND NOT id = ?", time_from, time_to, id).count > 0
      errors.add(:time_from, "shouldn't overlap with existing reservation")
    end
  end

  def valid_slot
    if !(table.restaurant.open?(time_from, time_to))
      errors.add(:time_from, "Invalid time slot #{time_from}")
      errors.add(:time_to, "Invalid time slot #{time_to}")
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:time_from, :time_to)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, local: true) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :time_from %>
    <%= form.datetime_select :time_from, id: :reservation_time_from %>
  </div>

  <div class="field">
    <%= form.label :time_to %>
    <%= form.datetime_select :time_to, id: :reservation_time_to %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/_reservation.html.erb
<tr>
	<td><%= reservation.time_from.strftime('%H:%M %d-%b-%y') %></td>
	<td><%= reservation.time_to.strftime('%H:%M %d-%b-%y') %></td>
	<td><%= link_to 'Show', reservation %></td>
	<td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
	<td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Time from</th>
      <th>Time to</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @reservations %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Restaurant:</strong>
  <%= @reservation.table.restaurant.name %>
</p>

<p>
  <strong>Table:</strong>
  <%= @reservation.table.name %>
</p>

<p>
  <strong>Time from:</strong>
  <%= @reservation.time_from.strftime('%H:%M %d-%b-%y') %>
</p>

<p>
  <strong>Time to:</strong>
  <%= @reservation.time_to.strftime('%H:%M %d-%b-%y') %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>